# Generated by Django 2.1.2 on 2018-12-06 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WIMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('DonationDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=45)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=50)),
                ('InStock', models.IntegerField()),
                ('ARV', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=45)),
                ('ProjectZip', models.IntegerField()),
                ('ProjectState', models.IntegerField()),
                ('DateProposed', models.DateField(null=True)),
                ('DateAccepted', models.DateField(blank=True, default=None, null=True)),
                ('DateCompleted', models.DateField(blank=True, default=None, null=True)),
                ('ProjectLocation', models.TextField()),
                ('ProjectDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityNeeded', models.IntegerField()),
                ('QuantityAcquired', models.IntegerField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIMS.Item')),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIMS.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectLead', models.BinaryField()),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIMS.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='projectmembers',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='DonorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WIMS.Item'),
        ),
    ]
